package:
  name: tenc
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
source:
  path: ../
requirements:
  build:
    - python
    - setuptools
    - zlib
  run:
    - python
    - zlib
    - numpy
    - scipy
    - nltk
    - configobj
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
about:
  home: https://github.com/mnick/10c
  license: GPLv3
